server:
  port: 8080
spring:
  r2dbc:
    pool:
      enabled: true
      max-size: 20
      validation-query: SELECT 1
      initial-size: 5
      max-idle-time: 30m
  data:
    r2dbc:
      repositories:
        enabled: true